[[redirects]]
  from = "/api/*"
  to = "http://webtruyentranh-306793996.ap-southeast-1.elb.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200